remote_theme: chrisrhymes/bulma-clean-theme
title: TACO: The Tensor Algebra Compiler
tagline: TACO: The Tensor Algebra Compiler
description:  A fast and versatile library for linear and tensor algebra
