// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
// taco "A(i,j)=B(i,j)+C(i,j)" -f=A:ds:0,1 -f=B:ds:0,1 -f=C:ds:0,1 -write-source=taco_kernel.c -write-compute=taco_compute.c -write-assembly=taco_assembly.c
#ifndef TACO_C_HEADERS
#define TACO_C_HEADERS
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <math.h>
#define TACO_MIN(_a,_b) ((_a) < (_b) ? (_a) : (_b))
#ifndef TACO_TENSOR_T_DEFINED
#define TACO_TENSOR_T_DEFINED
typedef enum { taco_dim_dense, taco_dim_sparse } taco_dim_t;
typedef struct {
  int32_t     order;      // tensor order (number of dimensions)
  int32_t*    dims;       // tensor dimensions
  taco_dim_t* dim_types;  // dimension storage types
  int32_t     csize;      // component size
  int32_t*    dim_order;  // dimension storage order
  uint8_t***  indices;    // tensor index data (per dimension)
  uint8_t*    vals;       // tensor values
} taco_tensor_t;
#endif
#endif

int assemble(taco_tensor_t *A, taco_tensor_t *B, taco_tensor_t *C) {
  int A1_size = *(int*)(A->indices[0][0]);
  int* restrict A2_pos = (int*)(A->indices[1][0]);
  int* restrict A2_idx = (int*)(A->indices[1][1]);
  double* restrict A_vals = (double*)(A->vals);
  int B1_size = *(int*)(B->indices[0][0]);
  int* restrict B2_pos = (int*)(B->indices[1][0]);
  int* restrict B2_idx = (int*)(B->indices[1][1]);
  int C1_size = *(int*)(C->indices[0][0]);
  int* restrict C2_pos = (int*)(C->indices[1][0]);
  int* restrict C2_idx = (int*)(C->indices[1][1]);

  /* init_alloc_size should be initialized to a power of two */
  int32_t init_alloc_size = 1048576;
  A2_pos = (int*)malloc(sizeof(int) * init_alloc_size);
  A2_idx = (int*)malloc(sizeof(int) * init_alloc_size);
  A2_pos[0] = 0;

  int32_t pA1 = 0;
  int32_t pA2 = A2_pos[pA1];
  for (int32_t iB = 0; iB < B1_size; iB++) {
    int32_t pB2 = B2_pos[iB];
    int32_t pC2 = C2_pos[iB];
    while ((pB2 < B2_pos[iB + 1]) && (pC2 < C2_pos[iB + 1])) {
      int32_t jB = B2_idx[pB2];
      int32_t jC = C2_idx[pC2];
      int32_t j = TACO_MIN(jB,jC);
      if ((jB == j) && (jC == j)) {
        A2_idx[pA2] = j;
        pA2++;
        if ((0 == ((pA2 + 1) & pA2)) && (init_alloc_size <= (pA2 + 1)))
          A2_idx = (int*)realloc(A2_idx, sizeof(int) * (2 * (pA2 + 1)));
      }
      else if (jB == j) {
        A2_idx[pA2] = j;
        pA2++;
        if ((0 == ((pA2 + 1) & pA2)) && (init_alloc_size <= (pA2 + 1)))
          A2_idx = (int*)realloc(A2_idx, sizeof(int) * (2 * (pA2 + 1)));
      }
      else {
        A2_idx[pA2] = j;
        pA2++;
        if ((0 == ((pA2 + 1) & pA2)) && (init_alloc_size <= (pA2 + 1)))
          A2_idx = (int*)realloc(A2_idx, sizeof(int) * (2 * (pA2 + 1)));
      }
      if (jB == j) pB2++;
      if (jC == j) pC2++;
    }
    while (pB2 < B2_pos[iB + 1]) {
      int32_t jB = B2_idx[pB2];
      A2_idx[pA2] = jB;
      pA2++;
      if ((0 == ((pA2 + 1) & pA2)) && (init_alloc_size <= (pA2 + 1)))
        A2_idx = (int*)realloc(A2_idx, sizeof(int) * (2 * (pA2 + 1)));
      pB2++;
    }
    while (pC2 < C2_pos[iB + 1]) {
      int32_t jC = C2_idx[pC2];
      A2_idx[pA2] = jC;
      pA2++;
      if ((0 == ((pA2 + 1) & pA2)) && (init_alloc_size <= (pA2 + 1)))
        A2_idx = (int*)realloc(A2_idx, sizeof(int) * (2 * (pA2 + 1)));
      pC2++;
    }
    A2_pos[(iB + 1)] = pA2;
  }

  A_vals = (double*)malloc(sizeof(double) * pA2);

  A->indices[1][0] = (uint8_t*)(A2_pos);
  A->indices[1][1] = (uint8_t*)(A2_idx);
  A->vals = (uint8_t*)A_vals;
  return 0;
}

int compute(taco_tensor_t *A, taco_tensor_t *B, taco_tensor_t *C) {
  int A1_size = *(int*)(A->indices[0][0]);
  int* restrict A2_pos = (int*)(A->indices[1][0]);
  double* restrict A_vals = (double*)(A->vals);
  int B1_size = *(int*)(B->indices[0][0]);
  int* restrict B2_pos = (int*)(B->indices[1][0]);
  int* restrict B2_idx = (int*)(B->indices[1][1]);
  double* restrict B_vals = (double*)(B->vals);
  int C1_size = *(int*)(C->indices[0][0]);
  int* restrict C2_pos = (int*)(C->indices[1][0]);
  int* restrict C2_idx = (int*)(C->indices[1][1]);
  double* restrict C_vals = (double*)(C->vals);

  int32_t pA1 = 0;
  int32_t pA2 = A2_pos[pA1];
  for (int32_t iB = 0; iB < B1_size; iB++) {
    int32_t pB2 = B2_pos[iB];
    int32_t pC2 = C2_pos[iB];
    while ((pB2 < B2_pos[iB + 1]) && (pC2 < C2_pos[iB + 1])) {
      int32_t jB = B2_idx[pB2];
      int32_t jC = C2_idx[pC2];
      int32_t j = TACO_MIN(jB,jC);
      if ((jB == j) && (jC == j)) {
        A_vals[pA2] = B_vals[pB2] + C_vals[pC2];
        pA2++;
      }
      else if (jB == j) {
        A_vals[pA2] = B_vals[pB2];
        pA2++;
      }
      else {
        A_vals[pA2] = C_vals[pC2];
        pA2++;
      }
      if (jB == j) pB2++;
      if (jC == j) pC2++;
    }
    while (pB2 < B2_pos[iB + 1]) {
      int32_t jB = B2_idx[pB2];
      A_vals[pA2] = B_vals[pB2];
      pA2++;
      pB2++;
    }
    while (pC2 < C2_pos[iB + 1]) {
      int32_t jC = C2_idx[pC2];
      A_vals[pA2] = C_vals[pC2];
      pA2++;
      pC2++;
    }
  }

  return 0;
}
