// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
int32_t pA1 = 0;
int32_t pA2 = A2_pos[pA1];
for (int32_t iB = 0; iB < B1_size; iB++) {
  int32_t pB2 = B2_pos[iB];
  int32_t pC2 = C2_pos[iB];
  while ((pB2 < B2_pos[iB + 1]) && (pC2 < C2_pos[iB + 1])) {
    int32_t jB = B2_idx[pB2];
    int32_t jC = C2_idx[pC2];
    int32_t j = min(jB, jC);
    if ((jB == j) && (jC == j)) {
      A_vals[pA2] = B_vals[pB2] + C_vals[pC2];
      pA2++;
    }
    else if (jB == j) {
      A_vals[pA2] = B_vals[pB2];
      pA2++;
    }
    else {
      A_vals[pA2] = C_vals[pC2];
      pA2++;
    }
    if (jB == j) pB2++;
    if (jC == j) pC2++;
  }
  while (pB2 < B2_pos[iB + 1]) {
    int32_t jB0 = B2_idx[pB2];
    A_vals[pA2] = B_vals[pB2];
    pA2++;
    pB2++;
  }
  while (pC2 < C2_pos[iB + 1]) {
    int32_t jC0 = C2_idx[pC2];
    A_vals[pA2] = C_vals[pC2];
    pA2++;
    pC2++;
  }
}