// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
/* init_alloc_size should be initialized to a power of two */
int32_t init_alloc_size = 1048576;
allocate A2_pos[init_alloc_size]
allocate A2_idx[init_alloc_size]
A2_pos[0] = 0;

int32_t pA1 = 0;
int32_t pA2 = A2_pos[pA1];
for (int32_t iB = 0; iB < B1_size; iB++) {
  int32_t pB2 = B2_pos[iB];
  int32_t pC2 = C2_pos[iB];
  while ((pB2 < B2_pos[iB + 1]) && (pC2 < C2_pos[iB + 1])) {
    int32_t jB = B2_idx[pB2];
    int32_t jC = C2_idx[pC2];
    int32_t j = min(jB, jC);
    if ((jB == j) && (jC == j)) {
      A2_idx[pA2] = j;
      pA2++;
      if ((0 == ((pA2 + 1) & pA2)) && (init_alloc_size <= (pA2 + 1)))
        reallocate A2_idx[(2 * (pA2 + 1))]
    }
    else if (jB == j) {
      A2_idx[pA2] = j;
      pA2++;
      if ((0 == ((pA2 + 1) & pA2)) && (init_alloc_size <= (pA2 + 1)))
        reallocate A2_idx[(2 * (pA2 + 1))]
    }
    else {
      A2_idx[pA2] = j;
      pA2++;
      if ((0 == ((pA2 + 1) & pA2)) && (init_alloc_size <= (pA2 + 1)))
        reallocate A2_idx[(2 * (pA2 + 1))]
    }
    if (jB == j) pB2++;
    if (jC == j) pC2++;
  }
  while (pB2 < B2_pos[iB + 1]) {
    int32_t jB0 = B2_idx[pB2];
    A2_idx[pA2] = jB0;
    pA2++;
    if ((0 == ((pA2 + 1) & pA2)) && (init_alloc_size <= (pA2 + 1)))
      reallocate A2_idx[(2 * (pA2 + 1))]
    pB2++;
  }
  while (pC2 < C2_pos[iB + 1]) {
    int32_t jC0 = C2_idx[pC2];
    A2_idx[pA2] = jC0;
    pA2++;
    if ((0 == ((pA2 + 1) & pA2)) && (init_alloc_size <= (pA2 + 1)))
      reallocate A2_idx[(2 * (pA2 + 1))]
    pC2++;
  }
  A2_pos[(iB + 1)] = pA2;
}

allocate A_vals[pA2]