// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
for (int32_t pA = 0; pA < (A1_size * A2_size); pA++) {
  A_vals[pA] = 0;
}
for (int32_t pB1 = B1_pos[0]; pB1 < B1_pos[1]; pB1++) {
  int32_t iB = B1_idx[pB1];
  for (int32_t pB2 = B2_pos[pB1]; pB2 < B2_pos[pB1 + 1]; pB2++) {
    int32_t kB = B2_idx[pB2];
    for (int32_t pB3 = B3_pos[pB2]; pB3 < B3_pos[pB2 + 1]; pB3++) {
      int32_t lB = B3_idx[pB3];
      double tl = B_vals[pB3];
      for (int32_t jC = 0; jC < C2_size; jC++) {
        int32_t pC2 = (kB * C2_size) + jC;
        int32_t pD2 = (lB * D2_size) + jC;
        int32_t pA2 = (iB * A2_size) + jC;
        A_vals[pA2] = A_vals[pA2] + ((tl * C_vals[pC2]) * D_vals[pD2]);
      }
    }
  }
}