// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
// taco "y(i)=A(i,j)*x(j)" -f=y:d:0 -f=A:ds:0,1 -f=x:d:0 -write-source=taco_kernel.c -write-compute=taco_compute.c -write-assembly=taco_assembly.c
#ifndef TACO_C_HEADERS
#define TACO_C_HEADERS
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <math.h>
#define TACO_MIN(_a,_b) ((_a) < (_b) ? (_a) : (_b))
#ifndef TACO_TENSOR_T_DEFINED
#define TACO_TENSOR_T_DEFINED
typedef enum { taco_dim_dense, taco_dim_sparse } taco_dim_t;
typedef struct {
  int32_t     order;      // tensor order (number of dimensions)
  int32_t*    dims;       // tensor dimensions
  taco_dim_t* dim_types;  // dimension storage types
  int32_t     csize;      // component size
  int32_t*    dim_order;  // dimension storage order
  uint8_t***  indices;    // tensor index data (per dimension)
  uint8_t*    vals;       // tensor values
} taco_tensor_t;
#endif
#endif

int assemble(taco_tensor_t *y, taco_tensor_t *A, taco_tensor_t *x) {
  int y1_size = *(int*)(y->indices[0][0]);
  double* restrict y_vals = (double*)(y->vals);

  y_vals = (double*)malloc(sizeof(double) * y1_size);

  y->vals = (uint8_t*)y_vals;
  return 0;
}

int compute(taco_tensor_t *y, taco_tensor_t *A, taco_tensor_t *x) {
  int y1_size = *(int*)(y->indices[0][0]);
  double* restrict y_vals = (double*)(y->vals);
  int A1_size = *(int*)(A->indices[0][0]);
  int* restrict A2_pos = (int*)(A->indices[1][0]);
  int* restrict A2_idx = (int*)(A->indices[1][1]);
  double* restrict A_vals = (double*)(A->vals);
  int x1_size = *(int*)(x->indices[0][0]);
  double* restrict x_vals = (double*)(x->vals);

  #pragma omp parallel for
  for (int32_t iA = 0; iA < A1_size; iA++) {
    double tj = 0;
    for (int32_t pA2 = A2_pos[iA]; pA2 < A2_pos[iA + 1]; pA2++) {
      int32_t jA = A2_idx[pA2];
      tj += A_vals[pA2] * x_vals[jA];
    }
    y_vals[iA] = tj;
  }

  return 0;
}
