// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
for (int32_t iA = 0; iA < A1_size; iA++) {
  double tj = 0;
  for (int32_t pA2 = A2_pos[iA]; pA2 < A2_pos[iA + 1]; pA2++) {
    int32_t jA = A2_idx[pA2];
    tj += A_vals[pA2] * x_vals[jA];
  }
  y_vals[iA] = tj;
}