// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
int32_t pA1 = A1_pos[0];
int32_t pA2 = A2_pos[pA1];
for (int32_t pB1 = B1_pos[0]; pB1 < B1_pos[1]; pB1++) {
  int32_t iB = B1_idx[pB1];
  for (int32_t pB2 = B2_pos[pB1]; pB2 < B2_pos[pB1 + 1]; pB2++) {
    int32_t jB = B2_idx[pB2];
    double tk = 0;
    for (int32_t pB3 = B3_pos[pB2]; pB3 < B3_pos[pB2 + 1]; pB3++) {
      int32_t kB = B3_idx[pB3];
      tk += B_vals[pB3] * c_vals[kB];
    }
    A_vals[pA2] = tk;
    pA2++;
  }
  if (A2_pos[pA1 + 1] > A2_pos[pA1]) pA1++;
}