// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
// taco "A(i,j)=B(i,j,k)*c(k)" -f=A:ss:0,1 -f=B:sss:0,1,2 -f=c:d:0 -write-source=taco_kernel.c -write-compute=taco_compute.c -write-assembly=taco_assembly.c

int assemble(taco_tensor_t *A, taco_tensor_t *B, taco_tensor_t *c) {
  int* restrict A1_pos = (int*)(A->indices[0][0]);
  int* restrict A1_crd = (int*)(A->indices[0][1]);
  int* restrict A2_pos = (int*)(A->indices[1][0]);
  int* restrict A2_crd = (int*)(A->indices[1][1]);
  double* restrict A_vals = (double*)(A->vals);
  int* restrict B1_pos = (int*)(B->indices[0][0]);
  int* restrict B1_crd = (int*)(B->indices[0][1]);
  int* restrict B2_pos = (int*)(B->indices[1][0]);
  int* restrict B2_crd = (int*)(B->indices[1][1]);

  A1_pos = (int32_t*)malloc(sizeof(int32_t) * 2);
  A1_pos[0] = 0;
  int32_t A1_crd_size = 1048576;
  A1_crd = (int32_t*)malloc(sizeof(int32_t) * A1_crd_size);
  int32_t iA = 0;
  int32_t A2_pos_size = 1048576;
  A2_pos = (int32_t*)malloc(sizeof(int32_t) * A2_pos_size);
  A2_pos[0] = 0;
  int32_t A2_crd_size = 1048576;
  A2_crd = (int32_t*)malloc(sizeof(int32_t) * A2_crd_size);
  int32_t jA = 0;


  for (int32_t iB = B1_pos[0]; iB < B1_pos[1]; iB++) {
    int32_t i = B1_crd[iB];
    int32_t pA2_begin = jA;
    if (A2_pos_size <= iA + 1) {
      A2_pos = (int32_t*)realloc(A2_pos, sizeof(int32_t) * (A2_pos_size * 2));
      A2_pos_size *= 2;
    }

    for (int32_t jB = B2_pos[iB]; jB < B2_pos[(iB + 1)]; jB++) {
      int32_t j = B2_crd[jB];
      if (A2_crd_size <= jA) {
        A2_crd = (int32_t*)realloc(A2_crd, sizeof(int32_t) * (A2_crd_size * 2));
        A2_crd_size *= 2;
      }
      A2_crd[jA] = j;
      jA++;
    }

    A2_pos[iA + 1] = jA;
    if (pA2_begin < jA) {
      if (A1_crd_size <= iA) {
        A1_crd = (int32_t*)realloc(A1_crd, sizeof(int32_t) * (A1_crd_size * 2));
        A1_crd_size *= 2;
      }
      A1_crd[iA] = i;
      iA++;
    }
  }

  A1_pos[1] = iA;

  A_vals = (double*)malloc(sizeof(double) * jA);

  A->indices[0][0] = (uint8_t*)(A1_pos);
  A->indices[0][1] = (uint8_t*)(A1_crd);
  A->indices[1][0] = (uint8_t*)(A2_pos);
  A->indices[1][1] = (uint8_t*)(A2_crd);
  A->vals = (uint8_t*)A_vals;
  return 0;
}
