// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
// taco "A(i,j)=B(i,j,k)*c(k)" -f=A:ss:0,1 -f=B:sss:0,1,2 -f=c:d:0 -write-source=taco_kernel.c -write-compute=taco_compute.c -write-assembly=taco_assembly.c
#ifndef TACO_C_HEADERS
#define TACO_C_HEADERS
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <math.h>
#define TACO_MIN(_a,_b) ((_a) < (_b) ? (_a) : (_b))
#ifndef TACO_TENSOR_T_DEFINED
#define TACO_TENSOR_T_DEFINED
typedef enum { taco_dim_dense, taco_dim_sparse } taco_dim_t;
typedef struct {
  int32_t     order;      // tensor order (number of dimensions)
  int32_t*    dims;       // tensor dimensions
  taco_dim_t* dim_types;  // dimension storage types
  int32_t     csize;      // component size
  int32_t*    dim_order;  // dimension storage order
  uint8_t***  indices;    // tensor index data (per dimension)
  uint8_t*    vals;       // tensor values
} taco_tensor_t;
#endif
#endif

int assemble(taco_tensor_t *A, taco_tensor_t *B, taco_tensor_t *c) {
  int* restrict A0_pos_arr = (int*)(A->indices[0][0]);
  int* restrict A0_idx_arr = (int*)(A->indices[0][1]);
  int* restrict A1_pos_arr = (int*)(A->indices[1][0]);
  int* restrict A1_idx_arr = (int*)(A->indices[1][1]);
  double* restrict A_val_arr = (double*)(A->vals);
  int* restrict B0_pos_arr = (int*)(B->indices[0][0]);
  int* restrict B0_idx_arr = (int*)(B->indices[0][1]);
  int* restrict B1_pos_arr = (int*)(B->indices[1][0]);
  int* restrict B1_idx_arr = (int*)(B->indices[1][1]);
  int* restrict B2_pos_arr = (int*)(B->indices[2][0]);
  int* restrict B2_idx_arr = (int*)(B->indices[2][1]);
  int c0_size = *(int*)(c->indices[0][0]);

  /* init_alloc_size should be initialized to a power of two */
  int32_t init_alloc_size = 1048576;
  A0_pos_arr = (int*)malloc(sizeof(int) * init_alloc_size);
  A0_idx_arr = (int*)malloc(sizeof(int) * init_alloc_size);
  A0_pos_arr[0] = 0;
  A1_pos_arr = (int*)malloc(sizeof(int) * init_alloc_size);
  A1_idx_arr = (int*)malloc(sizeof(int) * init_alloc_size);
  A1_pos_arr[0] = 0;

  int32_t A0_pos = A0_pos_arr[0];
  int32_t A1_pos = A1_pos_arr[A0_pos];
  for (int32_t B0_pos = B0_pos_arr[0]; B0_pos < B0_pos_arr[1]; B0_pos++) {
    int32_t iB = B0_idx_arr[B0_pos];
    for (int32_t B1_pos = B1_pos_arr[B0_pos]; B1_pos < B1_pos_arr[B0_pos + 1]; B1_pos++) {
      int32_t jB = B1_idx_arr[B1_pos];
      for (int32_t B2_pos = B2_pos_arr[B1_pos]; B2_pos < B2_pos_arr[B1_pos + 1]; B2_pos++) {
        int32_t kB = B2_idx_arr[B2_pos];

      }
      A1_idx_arr[A1_pos] = jB;
      A1_pos++;
      if ((0 == ((A1_pos + 1) & A1_pos)) && (init_alloc_size <= (A1_pos + 1)))
        A1_idx_arr = (int*)realloc(A1_idx_arr, sizeof(int) * (2 * (A1_pos + 1)));
    }
    A1_pos_arr[(A0_pos + 1)] = A1_pos;
    A0_idx_arr[A0_pos] = iB;
    if (A1_pos_arr[A0_pos + 1] > A1_pos_arr[A0_pos]) {
      A0_pos++;
      if ((0 == ((A0_pos + 1) & A0_pos)) && (init_alloc_size <= (A0_pos + 1))) {
        A0_idx_arr = (int*)realloc(A0_idx_arr, sizeof(int) * (2 * (A0_pos + 1)));
        A1_pos_arr = (int*)realloc(A1_pos_arr, sizeof(int) * (2 * (A0_pos + 1)));
      }
    }
  }
  A0_pos_arr[1] = A0_pos;

  A_val_arr = (double*)malloc(sizeof(double) * A1_pos);

  A->indices[0][0] = (uint8_t*)(A0_pos_arr);
  A->indices[0][1] = (uint8_t*)(A0_idx_arr);
  A->indices[1][0] = (uint8_t*)(A1_pos_arr);
  A->indices[1][1] = (uint8_t*)(A1_idx_arr);
  A->vals = (uint8_t*)A_val_arr;
  return 0;
}

int compute(taco_tensor_t *A, taco_tensor_t *B, taco_tensor_t *c) {
  int* restrict A0_pos_arr = (int*)(A->indices[0][0]);
  int* restrict A1_pos_arr = (int*)(A->indices[1][0]);
  double* restrict A_val_arr = (double*)(A->vals);
  int* restrict B0_pos_arr = (int*)(B->indices[0][0]);
  int* restrict B0_idx_arr = (int*)(B->indices[0][1]);
  int* restrict B1_pos_arr = (int*)(B->indices[1][0]);
  int* restrict B1_idx_arr = (int*)(B->indices[1][1]);
  int* restrict B2_pos_arr = (int*)(B->indices[2][0]);
  int* restrict B2_idx_arr = (int*)(B->indices[2][1]);
  double* restrict B_val_arr = (double*)(B->vals);
  int c0_size = *(int*)(c->indices[0][0]);
  double* restrict c_val_arr = (double*)(c->vals);

  int32_t A0_pos = A0_pos_arr[0];
  int32_t A1_pos = A1_pos_arr[A0_pos];
  for (int32_t B0_pos = B0_pos_arr[0]; B0_pos < B0_pos_arr[1]; B0_pos++) {
    int32_t iB = B0_idx_arr[B0_pos];
    for (int32_t B1_pos = B1_pos_arr[B0_pos]; B1_pos < B1_pos_arr[B0_pos + 1]; B1_pos++) {
      int32_t jB = B1_idx_arr[B1_pos];
      double tk = 0;
      for (int32_t B2_pos = B2_pos_arr[B1_pos]; B2_pos < B2_pos_arr[B1_pos + 1]; B2_pos++) {
        int32_t kB = B2_idx_arr[B2_pos];
        tk += B_val_arr[B2_pos] * c_val_arr[kB];
      }
      A_val_arr[A1_pos] = tk;
      A1_pos++;
    }
    if (A1_pos_arr[A0_pos + 1] > A1_pos_arr[A0_pos]) A0_pos++;
  }

  return 0;
}
